/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface MicroHome {
    }
    interface MicroProfile {
        "match": MatchResults;
    }
    interface MicroRoot {
    }
}
declare global {
    interface HTMLMicroHomeElement extends Components.MicroHome, HTMLStencilElement {
    }
    var HTMLMicroHomeElement: {
        prototype: HTMLMicroHomeElement;
        new (): HTMLMicroHomeElement;
    };
    interface HTMLMicroProfileElement extends Components.MicroProfile, HTMLStencilElement {
    }
    var HTMLMicroProfileElement: {
        prototype: HTMLMicroProfileElement;
        new (): HTMLMicroProfileElement;
    };
    interface HTMLMicroRootElement extends Components.MicroRoot, HTMLStencilElement {
    }
    var HTMLMicroRootElement: {
        prototype: HTMLMicroRootElement;
        new (): HTMLMicroRootElement;
    };
    interface HTMLElementTagNameMap {
        "micro-home": HTMLMicroHomeElement;
        "micro-profile": HTMLMicroProfileElement;
        "micro-root": HTMLMicroRootElement;
    }
}
declare namespace LocalJSX {
    interface MicroHome {
    }
    interface MicroProfile {
        "match"?: MatchResults;
    }
    interface MicroRoot {
    }
    interface IntrinsicElements {
        "micro-home": MicroHome;
        "micro-profile": MicroProfile;
        "micro-root": MicroRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "micro-home": LocalJSX.MicroHome & JSXBase.HTMLAttributes<HTMLMicroHomeElement>;
            "micro-profile": LocalJSX.MicroProfile & JSXBase.HTMLAttributes<HTMLMicroProfileElement>;
            "micro-root": LocalJSX.MicroRoot & JSXBase.HTMLAttributes<HTMLMicroRootElement>;
        }
    }
}
